language: c
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        packages:
        - qt
script:
- brew link qt5 --force
- cd project-files/qmake
- qmake
- make -j4
deploy:
  provider: releases
  api_key:
    secure: gBCdCIeICtS1A3zaET2rILd3yRNl6dXzLRCctbY8zKh3qNYIuzHqtMu9KqBv53XNbax/S31WMpjbIU1L+oo9JZItUdzkIUZu3cNRAmn73zTYiN0s3OMRCmpECk+woBwQa52L/Z+cNW9baTPZmM/1BfOsYty9nyHZPTMM+jGDEa5MolG9CW3wLCLO+MIr60uaYMoTpPAMz1XtH1830G18oGssPrtlrr0obfu0UCRvIFPrxl1g/6PJWCS33Yb3EzqtkHH13ux5exziUAKWpVRrECpFjvsBZna7p/Hetcyo6ZsCdL0xOrzRbKllRjt/wiNYMcePPzVF6tPqpzpLUMoXQXdzpgNqM5zBJuqmYrzGPKRY3CLgR6JoxXwCdEPvuFsjDeNGKidHCQiRfjpazAgvx+l//1K9UmJm7uB81cgMfRp1ZF9kmGZhLDwsSJucXE1mIx0qdD9hyto3D6rrY3CHqqinZOOOsqXSqayPWiu646CuzrW+XS13XJSrITE4JUj6Nkc3LaRYey/4dj/CYAtoQ+xPK1KoPl4rdYkwEBbRrhgRziXvl0Brb+Kvv1Z3Bm50nbDmeQF78JuaRit/Y+FK9ph8ajFXWIDLdDp7uM46tkbfrd1Cl8sFhPW/Ygai0yRkMG/aQ76ZZKapdoLLsloRJ4H9NkMNm/m/hEAMvs4v374=
  file: embroidermodder2.app
  on:
    repo: itsbalamurali/Embroidermodder
